In [49]:
import os

from math import sqrt

import numpy as np

import pandas as pd

from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score, classification_report, confusion_matrix

import troubled_life_all as tla
from troubled_life_all import TL

In [53]:
_, _, troubled_test_data = tla.load_all_data(
        clean_train_set=False,
        clean_val_set=False,
        troubled_test_set=True)

test_results = pd.read_csv(
    os.path.join(TL.OUTPUT_DIR,
                 'MV03R00_OV01R00_DP01R00_TR009_20180309-163927_SE000_EP398-00022.9634_results.csv'))

2018-03-10 10:33:18,409 - TROUBLED_LIFE - INFO - Loading prepared test data ...

2018-03-10 10:33:18,492 - TROUBLED_LIFE - INFO - Loading prepared test data done.

In [55]:
test_result[test_result["pred_correct"] == False]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>certainty</th>
      <th>label</th>
      <th>label_pred</th>
      <th>pol_mse</th>
      <th>pred_correct</th>
    </tr>
    <tr>
      <th>id</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2461</th>
      <td>128.328352</td>
      <td>False</td>
      <td>True</td>
      <td>129328.352399</td>
      <td>False</td>
    </tr>
  </tbody>
</table>
</div>

In [56]:
troubled_test_data.loc[2461]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>biz_proc</th>
      <th>tariff</th>
      <th>interest</th>
      <th>sum_insured</th>
      <th>premium</th>
      <th>current_capital</th>
      <th>troubled</th>
    </tr>
    <tr>
      <th>current_year</th>
      <th>version</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="4" valign="top">0</th>
      <th>0</th>
      <td>initial</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1177.876558</td>
      <td>0.000000</td>
      <td>False</td>
    </tr>
    <tr>
      <th>1</th>
      <td>collect_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1177.876558</td>
      <td>1177.876558</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>adapt_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1433.821787</td>
      <td>1177.876558</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>add_yearly_interest</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1433.821787</td>
      <td>1236.770386</td>
      <td>False</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">1</th>
      <th>1</th>
      <td>collect_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1433.821787</td>
      <td>2670.592172</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>adapt_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1846.756625</td>
      <td>2670.592172</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>add_yearly_interest</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1846.756625</td>
      <td>2804.121781</td>
      <td>False</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">2</th>
      <th>1</th>
      <td>collect_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>1846.756625</td>
      <td>4650.878406</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>adapt_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>2302.613252</td>
      <td>4650.878406</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>add_yearly_interest</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>2302.613252</td>
      <td>4883.422327</td>
      <td>False</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">3</th>
      <th>1</th>
      <td>collect_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>2302.613252</td>
      <td>7186.035579</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>add_yearly_interest</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>2302.613252</td>
      <td>7545.337358</td>
      <td>False</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">4</th>
      <th>1</th>
      <td>collect_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>2302.613252</td>
      <td>9847.950610</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>adapt_premium</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>2890.337418</td>
      <td>9847.950610</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>add_yearly_interest</td>
      <td>3</td>
      <td>0.05</td>
      <td>117787.655789</td>
      <td>2890.337418</td>
      <td>10340.348141</td>
      <td>False</td>
    </tr>
  </tbody>
</table>
</div>

In [45]:
test_result

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>certainty</th>
      <th>label</th>
      <th>label_pred</th>
      <th>pol_mse</th>
      <th>pred_correct</th>
    </tr>
    <tr>
      <th>id</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1001</th>
      <td>0.997660</td>
      <td>False</td>
      <td>False</td>
      <td>2.339968</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1002</th>
      <td>0.999244</td>
      <td>False</td>
      <td>False</td>
      <td>0.755994</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1003</th>
      <td>34.834023</td>
      <td>True</td>
      <td>True</td>
      <td>35834.022536</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1004</th>
      <td>0.970724</td>
      <td>False</td>
      <td>False</td>
      <td>29.276349</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1005</th>
      <td>6.613952</td>
      <td>True</td>
      <td>True</td>
      <td>7613.951724</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1006</th>
      <td>164.477633</td>
      <td>True</td>
      <td>True</td>
      <td>165477.633008</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1007</th>
      <td>0.998930</td>
      <td>False</td>
      <td>False</td>
      <td>1.070121</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1008</th>
      <td>0.995322</td>
      <td>False</td>
      <td>False</td>
      <td>4.677504</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1009</th>
      <td>0.998488</td>
      <td>False</td>
      <td>False</td>
      <td>1.512068</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1010</th>
      <td>0.995750</td>
      <td>False</td>
      <td>False</td>
      <td>4.249815</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1011</th>
      <td>145.740919</td>
      <td>True</td>
      <td>True</td>
      <td>146740.919186</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1012</th>
      <td>0.998836</td>
      <td>False</td>
      <td>False</td>
      <td>1.164211</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1013</th>
      <td>0.998624</td>
      <td>False</td>
      <td>False</td>
      <td>1.375572</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1014</th>
      <td>161.312309</td>
      <td>True</td>
      <td>True</td>
      <td>162312.309465</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1015</th>
      <td>0.998276</td>
      <td>False</td>
      <td>False</td>
      <td>1.723966</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1016</th>
      <td>0.997346</td>
      <td>False</td>
      <td>False</td>
      <td>2.654404</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1017</th>
      <td>84.529136</td>
      <td>True</td>
      <td>True</td>
      <td>85529.135815</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1018</th>
      <td>0.996738</td>
      <td>False</td>
      <td>False</td>
      <td>3.262376</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1019</th>
      <td>0.998742</td>
      <td>False</td>
      <td>False</td>
      <td>1.257904</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1020</th>
      <td>0.955189</td>
      <td>False</td>
      <td>False</td>
      <td>44.810506</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1021</th>
      <td>0.981625</td>
      <td>False</td>
      <td>False</td>
      <td>18.375040</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1022</th>
      <td>0.977989</td>
      <td>False</td>
      <td>False</td>
      <td>22.010886</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1023</th>
      <td>0.996107</td>
      <td>False</td>
      <td>False</td>
      <td>3.893195</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1024</th>
      <td>0.855489</td>
      <td>False</td>
      <td>False</td>
      <td>144.510617</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1025</th>
      <td>0.998533</td>
      <td>False</td>
      <td>False</td>
      <td>1.466823</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1026</th>
      <td>0.997895</td>
      <td>False</td>
      <td>False</td>
      <td>2.105202</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1027</th>
      <td>0.998404</td>
      <td>False</td>
      <td>False</td>
      <td>1.595818</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1028</th>
      <td>201.718404</td>
      <td>True</td>
      <td>True</td>
      <td>202718.403580</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1029</th>
      <td>0.998540</td>
      <td>False</td>
      <td>False</td>
      <td>1.460420</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1030</th>
      <td>0.977460</td>
      <td>False</td>
      <td>False</td>
      <td>22.540052</td>
      <td>True</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2971</th>
      <td>0.996843</td>
      <td>False</td>
      <td>False</td>
      <td>3.156517</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2972</th>
      <td>0.902791</td>
      <td>False</td>
      <td>False</td>
      <td>97.208965</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2973</th>
      <td>23.099854</td>
      <td>True</td>
      <td>True</td>
      <td>24099.853633</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2974</th>
      <td>0.997342</td>
      <td>False</td>
      <td>False</td>
      <td>2.658118</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2975</th>
      <td>0.994995</td>
      <td>False</td>
      <td>False</td>
      <td>5.004588</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2976</th>
      <td>0.998130</td>
      <td>False</td>
      <td>False</td>
      <td>1.869634</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2977</th>
      <td>61.260721</td>
      <td>True</td>
      <td>True</td>
      <td>62260.721188</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2978</th>
      <td>0.999145</td>
      <td>False</td>
      <td>False</td>
      <td>0.854866</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2979</th>
      <td>0.996750</td>
      <td>False</td>
      <td>False</td>
      <td>3.249578</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2980</th>
      <td>0.999320</td>
      <td>False</td>
      <td>False</td>
      <td>0.680482</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2981</th>
      <td>0.995494</td>
      <td>False</td>
      <td>False</td>
      <td>4.505650</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2982</th>
      <td>0.998517</td>
      <td>False</td>
      <td>False</td>
      <td>1.482969</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2983</th>
      <td>0.999325</td>
      <td>False</td>
      <td>False</td>
      <td>0.674967</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2984</th>
      <td>602.068996</td>
      <td>True</td>
      <td>True</td>
      <td>603068.995968</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2985</th>
      <td>0.998171</td>
      <td>False</td>
      <td>False</td>
      <td>1.828941</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2986</th>
      <td>0.997020</td>
      <td>False</td>
      <td>False</td>
      <td>2.980359</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2987</th>
      <td>70.161213</td>
      <td>True</td>
      <td>True</td>
      <td>71161.212695</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2988</th>
      <td>241.937199</td>
      <td>True</td>
      <td>True</td>
      <td>242937.198687</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2989</th>
      <td>0.998519</td>
      <td>False</td>
      <td>False</td>
      <td>1.481374</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2990</th>
      <td>138.464416</td>
      <td>True</td>
      <td>True</td>
      <td>139464.416412</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2991</th>
      <td>0.999193</td>
      <td>False</td>
      <td>False</td>
      <td>0.807082</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2992</th>
      <td>0.996546</td>
      <td>False</td>
      <td>False</td>
      <td>3.454294</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2993</th>
      <td>76.758387</td>
      <td>True</td>
      <td>True</td>
      <td>77758.387335</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2994</th>
      <td>24.278906</td>
      <td>True</td>
      <td>True</td>
      <td>25278.905744</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2995</th>
      <td>0.997060</td>
      <td>False</td>
      <td>False</td>
      <td>2.940299</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2996</th>
      <td>0.998343</td>
      <td>False</td>
      <td>False</td>
      <td>1.656746</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2997</th>
      <td>0.984693</td>
      <td>False</td>
      <td>False</td>
      <td>15.306661</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2998</th>
      <td>0.998234</td>
      <td>False</td>
      <td>False</td>
      <td>1.765640</td>
      <td>True</td>
    </tr>
    <tr>
      <th>2999</th>
      <td>0.998017</td>
      <td>False</td>
      <td>False</td>
      <td>1.983160</td>
      <td>True</td>
    </tr>
    <tr>
      <th>3000</th>
      <td>492.065760</td>
      <td>True</td>
      <td>True</td>
      <td>493065.759903</td>
      <td>True</td>
    </tr>
  </tbody>
</table>
<p>2000 rows × 5 columns</p>
</div>